version: 1
kind: environment
id: "env-production"
name: Production
variables:
  - key: meowfactsBaseUrl
    value: "https://meowfacts.herokuapp.com"
    enabled: true
  - key: httpbinBaseUrl
    value: "https://httpbin.org"
    enabled: true
