version: 1
kind: environment
id: "env-staging"
name: Staging
variables:
  - key: meowfactsBaseUrl
    value: "https://meowfacts.herokuapp.com"
    enabled: true
  - key: httpbinBaseUrl
    value: "{{HTTPBIN_BASE_URL}}"
    enabled: true
